-- public.requests definition

-- Drop table

-- DROP TABLE requests;

CREATE TABLE IF NOT EXISTS requests (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Идентификатор записи
    app varchar(150) NOT NULL, -- Идентификатор сервиса для которого записывается информация
    uri varchar(250) NOT NULL, -- URI для которого был осуществлен запрос
    ip varchar(150) NOT NULL, -- IP-адрес пользователя, осуществившего запрос
    time_stamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Дата и время, когда был совершен запрос к эндпоинту (в формате "yyyy-MM-dd HH:mm:ss")
    CONSTRAINT requests_pk PRIMARY KEY (id)
    );

-- Column comments

COMMENT ON COLUMN requests.id IS 'Идентификатор записи';
COMMENT ON COLUMN requests.app IS 'Идентификатор сервиса для которого записывается информация';
COMMENT ON COLUMN requests.uri IS 'URI для которого был осуществлен запрос';
COMMENT ON COLUMN requests.ip IS 'IP-адрес пользователя, осуществившего запрос';
COMMENT ON COLUMN requests.time_stamp IS 'Дата и время, когда был совершен запрос к эндпоинту (в формате yyyy-MM-dd HH:mm:ss)';